/* ===== İŞ HUKUKU (HBY230 4-9) — 150 TEST SORUSU + 100 AKIL KARTI =====
   a = doğru şıkkın indeksi (0=A,1=B,2=C,3=D) ; c = kategori */

const QUESTIONS = [
{c:"Fesih",q:"Belirli süreli iş sözleşmesinin feshinde 'haklı sebeple/derhal fesih' hangi maddelere dayanır?",o:["Madde 17 ve 18","Madde 24 ve 25","Madde 20 ve 21","Madde 26 ve 27"],a:1,e:"Haklı sebeple/derhal fesih İş Kanunu m.24 (işçi) ve m.25 (işveren) hükümlerine dayanır."},
{c:"Fesih",q:"İşverenin temerrüdü (işgörme edimini kabulde temerrüt) hangi düzenlemede yer alır?",o:["İş Kanunu m.17","TBK m.408","TBK m.439","İş Kanunu m.25"],a:1,e:"İşverenin temerrüdü Türk Borçlar Kanunu m.408'de düzenlenir; işçiye ücreti ödenir."},
{c:"Fesih",q:"TBK m.408'e göre işveren temerrüde düşerse işçinin başka iş yaparak kazandığı yararlar ne olur?",o:["İşçiye ayrıca ödenir","Ücretinden indirilir","Devlete aktarılır","Dikkate alınmaz"],a:1,e:"İşçinin yapmaktan kurtulduğu giderler ile kazandığı/kazanmaktan bilerek kaçındığı yararlar ücretinden indirilir."},
{c:"Fesih",q:"TBK m.439'a göre işçi haklı sebep olmaksızın aniden işi bırakırsa işveren ne kadar tazminat isteyebilir?",o:["Aylık ücretin yarısı","Aylık ücretin dörtte biri","Bir yıllık ücret","İki aylık ücret"],a:1,e:"İşveren aylık ücretin dörtte birine eşit tazminat isteyebilir; ek zararlar saklıdır."},
{c:"Fesih",q:"TBK m.439'a göre işverenin tazminat isteme hakkı kaç gün içinde kullanılmazsa düşer?",o:["7 gün","15 gün","30 gün","60 gün"],a:2,e:"İşveren bu hakkını işi bırakmadan başlayarak 30 gün içinde dava/takip yoluyla kullanmazsa hakkı düşer."},
{c:"Fesih",q:"İş Kanunu m.23'e göre yeni işverenin sorumluluğu hangi durumda DOĞMAZ?",o:["Yeni işveren bu davranışa sebep olmuşsa","Yeni işveren bilerek işe almışsa","Öğrendikten sonra çalıştırmaya devam ederse","Olaydan habersizse ve öğrenince işten çıkarırsa"],a:3,e:"Sorumluluk; sebep olma, bilerek alma veya öğrenince çalıştırmaya devam etme hâllerinde doğar."},
{c:"Fesih",q:"Süreli (bildirimli) fesih hakkını kimler kullanabilir?",o:["Yalnız işveren","Yalnız işçi","Hem işçi hem işveren","Yalnız sendika"],a:2,e:"Süreli fesih hem işçi hem işveren tarafından kullanılabilir; fesheden taraf diğerine bildirim yapar (m.17)."},
{c:"Fesih",q:"Madde 17'ye göre işi 6 aydan az sürmüş işçi için bildirim süresi kaç haftadır?",o:["2 hafta","4 hafta","6 hafta","8 hafta"],a:0,e:"6 aydan az kıdemde bildirim (önel) süresi 2 haftadır."},
{c:"Fesih",q:"İşi 6 ay – 1,5 yıl arası sürmüş işçi için bildirim süresi kaç haftadır?",o:["2 hafta","4 hafta","6 hafta","8 hafta"],a:1,e:"6 ay ile 1,5 yıl arası kıdemde bildirim süresi 4 haftadır."},
{c:"Fesih",q:"İşi 1,5 – 3 yıl arası sürmüş işçi için bildirim süresi kaç haftadır?",o:["2 hafta","4 hafta","6 hafta","8 hafta"],a:2,e:"1,5 yıl ile 3 yıl arası kıdemde bildirim süresi 6 haftadır."},
{c:"Fesih",q:"İşi 3 yıldan fazla sürmüş işçi için bildirim süresi kaç haftadır?",o:["4 hafta","6 hafta","8 hafta","12 hafta"],a:2,e:"3 yıldan fazla kıdemde bildirim süresi 8 haftadır. Ezber: 2-4-6-8."},
{c:"Fesih",q:"Madde 17'deki bildirim süreleri için doğru olan hangisidir?",o:["Azamidir, azaltılabilir","Asgaridir, sözleşmeyle artırılabilir","Değiştirilemez","Sadece işveren için geçerlidir"],a:1,e:"Süreler asgaridir; sözleşmelerle artırılabilir, azaltılamaz."},
{c:"Fesih",q:"İş güvencesi kapsamı dışındaki işçinin sözleşmesi fesih hakkı kötüye kullanılarak sona erdirilirse tazminat ne kadardır?",o:["Bildirim süresinin yarısı","Bildirim süresine eşit","Bildirim süresinin üç katı","Bir yıllık ücret"],a:2,e:"Kötüniyet hâlinde işçiye bildirim süresinin üç katı tutarında tazminat ödenir (m.17)."},
{c:"Fesih",q:"Çalışma koşullarında esaslı değişiklik hangi maddede düzenlenir ve işçi kaç günde yazılı kabul etmelidir?",o:["Madde 22 / 6 işgünü","Madde 17 / 2 hafta","Madde 25 / 6 iş günü","Madde 18 / 1 ay"],a:0,e:"Madde 22'ye göre esaslı değişiklik yazılı bildirilir; işçi 6 işgünü içinde yazılı kabul etmezse bağlamaz."},
{c:"Fesih",q:"İşçinin haklı nedenle derhal fesih hakkı hangi maddededir?",o:["Madde 17","Madde 24","Madde 25","Madde 26"],a:1,e:"İşçinin haklı nedenle derhal fesih hakkı Madde 24'te düzenlenir."},
{c:"Fesih",q:"İşçi için zorlayıcı sebeple haklı fesihte işyerinde işin ne kadar süreyle durması gerekir?",o:["Bir günden fazla","Bir haftadan fazla","Bir aydan fazla","Üç aydan fazla"],a:1,e:"İşçi, işyerinde bir haftadan fazla işin durmasını gerektiren zorlayıcı sebep hâlinde haklı fesih yapabilir (m.24/III)."},
{c:"Fesih",q:"İşverenin haklı nedenle derhal fesih hakkı hangi maddededir?",o:["Madde 17","Madde 24","Madde 25","Madde 26"],a:2,e:"İşverenin haklı nedenle derhal fesih hakkı Madde 25'te düzenlenir."},
{c:"Fesih",q:"Madde 25/I'e göre işçinin kendi kusurundan doğan hastalık nedeniyle ardı ardına kaç iş günü devamsızlık haklı fesih sebebidir?",o:["2 iş günü","3 iş günü","5 iş günü","7 iş günü"],a:1,e:"İşçinin kendi kastı/derli toplu olmayan yaşayışı/içkiden doğan hastalık nedeniyle ardı ardına 3 iş günü (veya ayda 5 iş gününden fazla) devamsızlık haklı fesih sebebidir."},
{c:"Fesih",q:"Madde 25/II'ye göre işçinin kaç günden fazla hapisle cezalandırılması (ertelenmeyen) haklı fesih sebebidir?",o:["3 günden fazla","5 günden fazla","7 günden fazla","10 günden fazla"],a:2,e:"İşçinin 7 günden fazla hapisle cezalandırılması ve cezanın ertelenmemesi işveren için haklı fesih sebebidir."},
{c:"Fesih",q:"Madde 25/II'ye göre izinsiz/haklı sebepsiz ardı ardına kaç işgünü devamsızlık haklı fesih sebebidir?",o:["2 işgünü","3 işgünü","5 işgünü","7 işgünü"],a:0,e:"İzinsiz/haklı sebepsiz ardı ardına 2 işgünü (veya ayda iki kez tatil sonrası işgünü ya da ayda 3 işgünü) devamsızlık haklı fesih sebebidir."},
{c:"Fesih",q:"Yalnızca işverenin haklı fesih sebepleri arasında sayılan, 24. maddede bulunmayan başlık hangisidir?",o:["Sağlık sebepleri","Zorlayıcı sebepler","İşçinin gözaltına alınması/tutuklanması","Ahlak ve iyiniyet kuralları"],a:2,e:"İşçinin gözaltına alınması/tutuklanması (devamsızlığın bildirim süresini aşması) yalnızca işverenin haklı fesih sebebidir (m.25/IV)."},
{c:"Fesih",q:"Derhal fesih hakkını kullanma süresi (Madde 26) öğrenme tarihinden itibaren kaç iş günüdür?",o:["3 iş günü","6 iş günü","10 iş günü","15 iş günü"],a:1,e:"Ahlak/iyiniyete aykırılık fesih yetkisi, öğrenme gününden başlayarak 6 iş günü geçtikten sonra kullanılamaz."},
{c:"Fesih",q:"Madde 26'ya göre fiilden itibaren hangi süre sonunda fesih yetkisi her hâlde kullanılamaz?",o:["6 ay","1 yıl","2 yıl","5 yıl"],a:1,e:"Her hâlde fiilin gerçekleşmesinden itibaren 1 yıl sonra fesih yetkisi kullanılamaz (maddi çıkar hâli hariç)."},
{c:"Fesih",q:"Madde 19'a göre işveren fesih bildirimini nasıl yapmak zorundadır?",o:["Sözlü olarak","Yazılı ve sebebini açık-kesin belirterek","Sadece tanık huzurunda","Noterden"],a:1,e:"İşveren fesih bildirimini yazılı yapmak ve sebebini açık ve kesin belirtmek zorundadır (m.19)."},
{c:"Fesih",q:"Feshe bağlı haklardan biri OLMAYAN hangisidir?",o:["İhbar tazminatı","Kıdem tazminatı","Yeni iş arama izni","Grev tazminatı"],a:3,e:"Feshe bağlı haklar: ihbar tazminatı, işe iade tazminatları, kıdem tazminatı, yeni iş arama izni. 'Grev tazminatı' yoktur."},
{c:"Fesih",q:"Kıdem tazminatı hâlâ yürürlükte olan hangi kanunun hangi maddesinde düzenlenir?",o:["4857 sayılı Kanun m.14","Mülga 1475 sayılı Kanun m.14","6356 sayılı Kanun m.14","TBK m.14"],a:1,e:"Kıdem tazminatı, mülga 1475 sayılı İş Kanunu'nun yürürlükteki tek maddesi olan 14. maddede düzenlenir."},
{c:"Fesih",q:"Kıdem tazminatı her tam yıl için ne kadar ücret tutarındadır?",o:["15 günlük ücret","30 günlük ücret","45 günlük ücret","60 günlük ücret"],a:1,e:"Her geçen tam yıl için 30 günlük ücret tutarında kıdem tazminatı ödenir; artan süreler orantılı."},
{c:"Fesih",q:"Kıdem tazminatına hak kazanmak için en az ne kadar çalışma gerekir ve hangi ücret esas alınır?",o:["6 ay / ilk ücret","1 yıl / son ücret","2 yıl / ortalama ücret","1 yıl / asgari ücret"],a:1,e:"En az 1 yıllık kıdem gerekir; hesap son ücret üzerinden yapılır."},
{c:"Fesih",q:"Kadın işçi evlendiği tarihten itibaren ne kadar süre içinde kendi isteğiyle ayrılırsa kıdem tazminatına hak kazanır?",o:["1 ay","6 ay","1 yıl","2 yıl"],a:2,e:"Kadın işçi evlendiği tarihten itibaren bir yıl içinde kendi arzusuyla ayrılırsa kıdem tazminatına hak kazanır."},
{c:"Fesih",q:"Kıdem tazminatı, ihbar tazminatı ve yıllık izin ücretinde zamanaşımı süresi kaç yıldır?",o:["2 yıl","5 yıl","10 yıl","1 yıl"],a:1,e:"4857 Ek Madde 3'e göre bu tazminat ve alacaklarda zamanaşımı 5 yıldır."},
{c:"Fesih",q:"Ücret kural olarak en geç hangi sürede ödenir (Madde 32)?",o:["Haftada bir","Ayda bir","İki ayda bir","Üç ayda bir"],a:1,e:"Ücret en geç ayda bir ödenir; sözleşmeyle bu süre bir haftaya kadar indirilebilir."},
{c:"Fesih",q:"Madde 34'e göre ücreti ödeme gününden kaç gün içinde ödenmeyen işçi iş görmekten kaçınabilir?",o:["10 gün","20 gün","30 gün","45 gün"],a:1,e:"Ücreti 20 gün içinde mücbir sebep dışında ödenmeyen işçi iş görme borcunu yerine getirmekten kaçınabilir (grev sayılmaz)."},
{c:"Fesih",q:"Madde 35'e göre işçi ücretinin ne kadarı haczedilemez?",o:["Tamamı","Yarısı","Dörtte birinden fazlası","Üçte ikisi"],a:2,e:"İşçi aylık ücretinin dörtte birinden fazlası haczedilemez veya devredilemez (nafaka alacakları hariç)."},
{c:"Fesih",q:"Yeni iş arama izni (Madde 27) günde en az kaç saat olmalıdır?",o:["1 saat","2 saat","3 saat","4 saat"],a:1,e:"Bildirim süresi içinde işveren günde en az 2 saat ücretli iş arama izni vermek zorundadır."},
{c:"Fesih",q:"İşveren iş arama izni esnasında işçiyi çalıştırırsa o sürenin ücretini nasıl öder?",o:["Normal","Yüzde 50 zamlı","Yüzde 100 zamlı","Ödemez"],a:2,e:"İş arama izninde çalıştırılan işçiye, alacağı ücrete ek olarak çalıştırılan sürenin ücreti %100 zamlı ödenir (m.27)."},
{c:"Fesih",q:"Toplu işçi çıkarmada (Madde 29) işveren durumu en az kaç gün önce bildirir?",o:["15 gün","30 gün","60 gün","90 gün"],a:1,e:"İşveren toplu işçi çıkarmayı en az 30 gün önce sendika temsilcilerine, bölge müdürlüğüne ve İŞKUR'a yazıyla bildirir."},
{c:"Fesih",q:"Madde 29'a göre 20-100 işçi çalıştıran işyerinde kaç işçinin çıkarılması toplu işçi çıkarma sayılır?",o:["En az 5","En az 10","En az 20","En az 30"],a:1,e:"20-100 işçi arasında en az 10 işçinin bir ay içinde çıkarılması toplu işçi çıkarma sayılır."},
{c:"Fesih",q:"Madde 29'a göre 301 ve daha fazla işçi çalıştıran işyerinde toplu çıkarma eşiği nedir?",o:["En az %10","En az 30 işçi","En az 50 işçi","En az %20"],a:1,e:"301 ve daha fazla işçide en az 30 işçinin çıkarılması toplu işçi çıkarmadır (101-300 arası ise en az %10)."},
{c:"İş Güvencesi",q:"İş güvencesi (geçerli sebep/işe iade) hangi maddeler arasında düzenlenir?",o:["Madde 8-11","Madde 18-21","Madde 24-26","Madde 63-66"],a:1,e:"İş güvencesi hükümleri Madde 18-21 arasında düzenlenir."},
{c:"İş Güvencesi",q:"İş güvencesinden yararlanmak için işyerinde en az kaç işçi olmalıdır?",o:["10","20","30","50"],a:2,e:"İş güvencesi için işyerinde en az 30 işçi çalıştırılması gerekir (m.18)."},
{c:"İş Güvencesi",q:"İş güvencesi için işçinin en az ne kadar kıdemi olmalıdır?",o:["1 ay","3 ay","6 ay","1 yıl"],a:2,e:"İş güvencesi için işçinin en az 6 aylık kıdemi olmalıdır."},
{c:"İş Güvencesi",q:"Yer altı işlerinde çalışan işçilerde iş güvencesi bakımından hangi şart aranmaz?",o:["30 işçi şartı","6 aylık kıdem şartı","Belirsiz süreli sözleşme","Geçerli sebep"],a:1,e:"Yer altı işlerinde çalışan işçilerde 6 aylık kıdem şartı aranmaz (m.18)."},
{c:"İş Güvencesi",q:"Aşağıdakilerden hangisi fesih için GEÇERLİ SEBEP oluşturmaz?",o:["İşletme gereği iş azalması","İşçinin yetersizliği","Sendika üyeliği/sendikal faaliyet","Performans düşüklüğü"],a:2,e:"Sendika üyeliği/faaliyeti, idari-adli başvuru, ırk-cinsiyet-din vb. geçerli sebep oluşturmaz (m.18)."},
{c:"İş Güvencesi",q:"İşe iade için işçi, fesih tebliğinden itibaren kaç sürede arabulucuya başvurmalıdır?",o:["1 hafta","1 ay","2 ay","3 ay"],a:1,e:"İşçi tebliğden itibaren 1 ay içinde işe iade talebiyle arabulucuya başvurmak zorundadır (m.20)."},
{c:"İş Güvencesi",q:"Arabuluculukta anlaşma olmazsa son tutanaktan itibaren kaç süre içinde dava açılır?",o:["1 hafta","2 hafta","1 ay","2 ay"],a:1,e:"Anlaşma sağlanamazsa son tutanaktan itibaren iki hafta içinde iş mahkemesinde dava açılır (m.20)."},
{c:"İş Güvencesi",q:"İş güvencesi davasında feshin geçerli sebebe dayandığını kim ispatlar?",o:["İşçi","İşveren","Arabulucu","Bakanlık"],a:1,e:"Feshin geçerli sebebe dayandığını ispat yükü işverene aittir (m.20)."},
{c:"İş Güvencesi",q:"Fesih geçersiz sayılırsa işveren işçiyi kaç sürede işe başlatmak zorundadır?",o:["10 gün","1 ay","2 ay","6 ay"],a:1,e:"Fesih geçersizse işveren işçiyi 1 ay içinde işe başlatmak zorundadır (m.21)."},
{c:"İş Güvencesi",q:"İşe başlatmayan işveren işçiye ne kadar iş güvencesi tazminatı öder?",o:["1-3 aylık ücret","4-8 aylık ücret","6-12 aylık ücret","Bir yıllık ücret"],a:1,e:"İşe başlatmama hâlinde işçiye en az 4, en çok 8 aylık ücreti tutarında tazminat ödenir (m.21)."},
{c:"İş Güvencesi",q:"Geçersiz fesihte boşta geçen süre için en çok kaç aya kadar ücret ödenir?",o:["2 ay","4 ay","6 ay","8 ay"],a:1,e:"Çalıştırılmadığı süre için en çok 4 aya kadar doğmuş ücret ve diğer hakları ödenir (m.21)."},
{c:"İş Güvencesi",q:"İşçi, kesinleşen işe iade kararının tebliğinden itibaren kaç işgünü içinde başvurmalıdır?",o:["6 işgünü","10 işgünü","15 işgünü","30 işgünü"],a:1,e:"İşçi kararın tebliğinden itibaren 10 işgünü içinde işe başlamak için işverene başvurmalıdır (m.21)."},
{c:"Çalışma Düzeni",q:"Genel bakımdan haftalık azami çalışma süresi kaç saattir (Madde 63)?",o:["40 saat","45 saat","48 saat","50 saat"],a:1,e:"Genel bakımdan çalışma süresi haftada en çok 45 saattir."},
{c:"Çalışma Düzeni",q:"Yer altı maden işlerinde çalışan işçilerin günlük ve haftalık azami çalışma süresi nedir?",o:["8 / 45 saat","7,5 / 37,5 saat","6 / 30 saat","7 / 40 saat"],a:1,e:"Yer altı maden işlerinde günde en çok 7,5, haftada en çok 37,5 saat çalışılır (m.63)."},
{c:"Çalışma Düzeni",q:"Denkleştirmede günlük çalışma süresi hiçbir şekilde kaç saati geçemez?",o:["9 saat","10 saat","11 saat","12 saat"],a:2,e:"Denkleştirmede günlük çalışma süresi 11 saati geçemez; dönem ortalaması 45 saattir."},
{c:"Çalışma Düzeni",q:"Denkleştirme süresi kural olarak ne kadardır, TİS ile ne kadara çıkar?",o:["1 ay / 2 ay","2 ay / 4 ay","3 ay / 6 ay","4 ay / 8 ay"],a:1,e:"Denkleştirme 2 ay; toplu iş sözleşmesiyle 4 aya kadar uzatılabilir (m.63)."},
{c:"Çalışma Düzeni",q:"Turizm sektöründe denkleştirme süresi ne kadardır, TİS ile ne kadara çıkar?",o:["2 ay / 4 ay","4 ay / 6 ay","3 ay / 6 ay","6 ay / 12 ay"],a:1,e:"Turizmde denkleştirme 4 ay; toplu iş sözleşmesiyle 6 aya kadar artırılabilir (m.63)."},
{c:"Çalışma Düzeni",q:"Telafi çalışması fazla çalışma sayılır mı, günde en çok kaç saattir?",o:["Sayılır / 2 saat","Sayılmaz / 3 saat","Sayılır / 3 saat","Sayılmaz / 2 saat"],a:1,e:"Telafi çalışması fazla çalışma sayılmaz; günde en çok 3 saat olabilir ve tatil günlerinde yaptırılamaz (m.64)."},
{c:"Çalışma Düzeni",q:"Telafi çalışmasına yol açan hâllerden biri OLMAYAN hangisidir?",o:["Zorunlu nedenle işin durması","Bayram/tatil çevresi işyeri tatili","İşçinin talebiyle izin","Haftalık 45 saati aşan rutin çalışma"],a:3,e:"45 saati aşan rutin çalışma fazla çalışmadır; telafi çalışması zorunlu durma, tatil çevresi ve işçi talebiyle izin hâllerinde söz konusudur."},
{c:"Çalışma Düzeni",q:"Kısa çalışma en çok kaç ayı geçmemek üzere uygulanır?",o:["1 ay","2 ay","3 ay","6 ay"],a:2,e:"Kısa çalışma, 3 ayı geçmemek üzere; çalışma süresinin en az 1/3 azaltılması veya en az 4 hafta faaliyetin durdurulmasıdır."},
{c:"Çalışma Düzeni",q:"4 saatten fazla ve 7,5 saate kadar (dâhil) süreli işlerde ara dinlenme ne kadardır (Madde 68)?",o:["15 dakika","Yarım saat","1 saat","45 dakika"],a:1,e:"4 saatten fazla ve 7,5 saate kadar süreli işlerde ara dinlenme yarım saattir."},
{c:"Çalışma Düzeni",q:"7,5 saatten fazla süreli işlerde ara dinlenme ne kadardır?",o:["15 dakika","Yarım saat","1 saat","1,5 saat"],a:2,e:"7,5 saatten fazla süreli işlerde ara dinlenme 1 saattir."},
{c:"Çalışma Düzeni",q:"Ara dinlenmeleri ile ilgili doğru olan hangisidir?",o:["Çalışma süresinden sayılır","Çalışma süresinden sayılmaz","Fazla çalışma sayılır","Ücretli izindir"],a:1,e:"Ara dinlenmeleri çalışma süresinden sayılmaz (m.68)."},
{c:"Çalışma Düzeni",q:"Çalışma hayatında 'gece' hangi saatler arasıdır (Madde 69)?",o:["22.00 - 05.00","20.00 - 06.00","21.00 - 07.00","19.00 - 06.00"],a:1,e:"Gece, en geç 20.00'de başlayıp en erken 06.00'ya kadar geçen ve en fazla 11 saat süren dönemdir."},
{c:"Çalışma Düzeni",q:"İşçilerin gece çalışması kural olarak kaç saati geçemez?",o:["6 saat","7,5 saat","8 saat","9 saat"],a:1,e:"Gece çalışması 7,5 saati geçemez; turizm, özel güvenlik ve sağlık işlerinde yazılı onayla istisna vardır (m.69)."},
{c:"Çalışma Düzeni",q:"Madde 71'e göre kural olarak kaç yaşını doldurmamış çocukların çalıştırılması yasaktır?",o:["12","14","15","18"],a:2,e:"15 yaşını doldurmamış çocukların çalıştırılması yasaktır (14 yaşını doldurup ilköğretimi tamamlayan hafif işlerde çalışabilir)."},
{c:"Çalışma Düzeni",q:"Madde 72'ye göre yer/su altı işlerinde kimlerin çalıştırılması yasaktır?",o:["Sadece 18 yaş altı erkekler","Sadece kadınlar","18 yaşını doldurmamış erkekler ve her yaştaki kadınlar","Sadece 16 yaş altı"],a:2,e:"Maden, kanalizasyon, tünel gibi yer/su altı işlerinde 18 yaşını doldurmamış erkek ve her yaştaki kadın çalıştırılamaz (m.72)."},
{c:"Çalışma Düzeni",q:"Madde 74'e göre kadın işçi doğumdan önce ve sonra toplam kaç hafta çalıştırılmaz?",o:["8 hafta","12 hafta","16 hafta","18 hafta"],a:2,e:"Doğumdan önce 8 ve sonra 8 olmak üzere toplam 16 hafta çalıştırılmaması esastır (çoğul gebelikte öncekine +2 hafta)."},
{c:"Çalışma Düzeni",q:"Süt izni (Madde 74) günde ne kadardır ve hangi yaşa kadar verilir?",o:["1 saat / 1 yaş","1,5 saat / 1 yaş","2 saat / 2 yaş","Yarım saat / 6 ay"],a:1,e:"1 yaşından küçük çocuğu emziren kadına günde toplam 1,5 saat süt izni verilir; bu süre çalışma süresinden sayılır."},
{c:"Çalışma Düzeni",q:"Doğum sonrası yarım çalışma için ücretsiz izin süresi birinci doğumda kaç gündür?",o:["30 gün","60 gün","120 gün","180 gün"],a:1,e:"Yarım çalışma ücretsiz izni birinci doğumda 60, ikincide 120, sonrakilerde 180 gündür (engelli çocukta 360)."},
{c:"Çalışma Düzeni",q:"Fazla çalışma haftalık kaç saati aşan çalışmadır ve ücreti nedir (Madde 41)?",o:["40 saat / %25","45 saat / %50","45 saat / %25","48 saat / %50"],a:1,e:"Fazla çalışma haftalık 45 saati aşan çalışmadır; her saat %50 zamlı ödenir."},
{c:"Çalışma Düzeni",q:"Fazla süreli çalışmanın ücreti nasıl ödenir?",o:["%25 zamlı","%50 zamlı","%75 zamlı","Zamsız"],a:0,e:"45 saatin altında belirlenmiş sürenin aşılıp 45'e kadar yapılması fazla süreli çalışmadır; %25 zamlı ödenir."},
{c:"Çalışma Düzeni",q:"Fazla çalışma karşılığı serbest zaman, her bir saat için ne kadardır?",o:["1 saat","1 saat 15 dakika","1 saat 30 dakika","2 saat"],a:2,e:"Fazla çalışmada her saat için 1 saat 30 dk; fazla süreli çalışmada 1 saat 15 dk serbest zaman kullanılır (6 ay içinde)."},
{c:"Çalışma Düzeni",q:"Fazla çalışma süresi toplamı bir yılda en çok kaç saat olabilir?",o:["180 saat","220 saat","270 saat","360 saat"],a:2,e:"Fazla çalışma süresi bir yılda 270 saatten fazla olamaz (m.41)."},
{c:"Çalışma Düzeni",q:"Fazla çalışma yaptırılabilmesi için ne gerekir?",o:["İşçinin onayı","Sendika kararı","Mahkeme izni","Bakanlık onayı"],a:0,e:"Fazla saatlerle çalışmak için işçinin onayının alınması gerekir (m.41)."},
{c:"Çalışma Düzeni",q:"Aşağıdakilerden hangisine fazla çalışma yaptırılamaz?",o:["25 yaşındaki erkek işçi","Kısmi süreli çalışan işçi","Tam süreli çalışan işçi","Vasıflı işçi"],a:1,e:"Kısmi süreli çalışanlara, 18 yaş altı, gebe/yeni doğum yapmış/emziren ve raporlu işçilere fazla çalışma yaptırılamaz (Yön. m.8)."},
{c:"Çalışma Düzeni",q:"Hafta tatili (Madde 46) 7 günlük dilimde kesintisiz en az kaç saat olmalıdır?",o:["12 saat","24 saat","36 saat","48 saat"],a:1,e:"İşçilere 7 günlük zaman diliminde kesintisiz en az 24 saat hafta tatili verilir."},
{c:"Çalışma Düzeni",q:"Mazeret izni (Ek Madde 2): işçinin evlenmesi veya çocuğunun ölümünde kaç gün izin verilir?",o:["1 gün","3 gün","5 gün","7 gün"],a:1,e:"Evlenme/evlat edinme veya ana-baba-eş-kardeş-çocuk ölümünde 3 gün ücretli izin verilir."},
{c:"Çalışma Düzeni",q:"Ek Madde 2'ye göre eşinin doğum yapması hâlinde işçiye kaç gün izin verilir?",o:["3 gün","5 gün","7 gün","10 gün"],a:1,e:"Eşin doğum yapması hâlinde işçiye 5 gün ücretli izin verilir."},
{c:"Çalışma Düzeni",q:"Yıllık ücretli izne hak kazanmak için işçi en az ne kadar çalışmış olmalıdır?",o:["6 ay","1 yıl","2 yıl","3 ay"],a:1,e:"Deneme süresi de dâhil en az 1 yıl çalışmış işçiye yıllık ücretli izin verilir (m.53)."},
{c:"Çalışma Düzeni",q:"Hizmet süresi 1-5 yıl (5 dâhil) olan işçiye yıllık izin en az kaç gündür?",o:["12 gün","14 gün","20 gün","26 gün"],a:1,e:"1-5 yıl (5 dâhil) hizmette yıllık izin en az 14 gündür."},
{c:"Çalışma Düzeni",q:"Hizmet süresi 15 yıl ve daha fazla olan işçiye yıllık izin en az kaç gündür?",o:["14 gün","20 gün","26 gün","30 gün"],a:2,e:"15 yıl (dâhil) ve daha fazla hizmette yıllık izin en az 26 gündür (5-15 arası 20 gün)."},
{c:"Çalışma Düzeni",q:"18 yaşından küçük ve 50 yaşından büyük işçilere yıllık izin en az kaç gün olmalıdır?",o:["14 gün","20 gün","26 gün","30 gün"],a:1,e:"18 ve daha küçük yaştaki işçilerle 50 ve daha yukarı yaştaki işçilere yıllık izin 20 günden az olamaz."},
{c:"Çalışma Düzeni",q:"Yıllık ücretli izin hakkı için doğru olan hangisidir?",o:["Devredilebilir","Vazgeçilemez","Paraya çevrilir","İşveren erteleyebilir"],a:1,e:"Yıllık ücretli izin hakkından vazgeçilemez (m.53)."},
{c:"Çalışma Düzeni",q:"Kısmi süreli çalışma, tam süreli emsal çalışmanın hangi oranına kadardır?",o:["Yarısı","Üçte ikisi (2/3)","Dörtte üçü","Beşte dördü"],a:1,e:"Kısmi süreli çalışma, emsal çalışmanın üçte ikisine (2/3) kadar yapılan çalışmadır."},
{c:"Çalışma Düzeni",q:"Emsal işçi 45 saat çalışıyorsa kısmi süreli çalışma kaç saat ve altıdır?",o:["20 saat","25 saat","30 saat","35 saat"],a:2,e:"45 saatin 2/3'ü = 30 saat; 30 saat ve altı kısmi sürelidir."},
{c:"İSG",q:"İş Sağlığı ve Güvenliği Kanunu'nun numarası kaçtır?",o:["4857","6356","6331","5510"],a:2,e:"İş Sağlığı ve Güvenliği Kanunu 6331 sayılıdır."},
{c:"İSG",q:"İşverenin iş sağlığı ve güvenliğini sağlama borcu hangi düzenlemede yer alır?",o:["TBK m.408","TBK m.417","İş K. m.41","6356 m.25"],a:1,e:"İşverenin İSG sağlama borcu TBK m.417/2'de düzenlenir; işçi de alınan önlemlere uymakla yükümlüdür."},
{c:"İSG",q:"İSG'nin iki ana ekseni hangisidir?",o:["Koruma ve Telafi","Prim ve Aylık","Grev ve Lokavt","İhbar ve Kıdem"],a:0,e:"İSG iki eksenlidir: Koruma (iş kazası/meslek hastalığını önleme - 6331) ve Telafi (sosyal sigorta - 5510)."},
{c:"İSG",q:"İş kazası 6331 sayılı Kanun'un hangi maddesinde tanımlanır?",o:["Madde 1","Madde 3","Madde 14","Madde 21"],a:1,e:"İş kazası 6331 sayılı Kanun'un 3. (Tanımlar) maddesinin (g) bendinde tanımlanır."},
{c:"İSG",q:"6331'e göre meslek hastalığı nedir?",o:["İşyerinde geçirilen her hastalık","Mesleki risklere maruziyet sonucu ortaya çıkan hastalık","Sadece kalıcı engellilik","Trafik kazası"],a:1,e:"6331 m.3/l'ye göre meslek hastalığı, mesleki risklere maruziyet sonucu ortaya çıkan hastalıktır."},
{c:"İSG",q:"5510 sayılı Kanun'un 14. maddesi neyi tanımlar?",o:["İş kazası","Meslek hastalığı","Hastalık","Analık"],a:1,e:"5510 m.14 meslek hastalığını; m.13 ise iş kazasını tanımlar."},
{c:"İSG",q:"İşverence sağlanan taşıtla işe gidiş-gelişte meydana gelen kaza nedir (5510 m.13)?",o:["İş kazası değildir","İş kazasıdır","Trafik kazasıdır","Meslek hastalığıdır"],a:1,e:"İşverence sağlanan taşıtla gidiş-gelişte meydana gelen olay iş kazası sayılır (5510 m.13/e)."},
{c:"İSG",q:"İş kazası, SGK'ya en geç kaç işgünü içinde bildirilmelidir?",o:["Derhal","3 işgünü","7 işgünü","1 ay"],a:1,e:"İş kazası kolluk kuvvetlerine derhal, Kuruma da en geç kazadan sonraki 3 işgünü içinde bildirilir (5510 m.13)."},
{c:"İSG",q:"İş kazası sigortasından yararlanmak için prim günü bakımından durum nedir?",o:["90 gün gerekir","180 gün gerekir","Prim günü sınırı aranmaz","1 yıl gerekir"],a:2,e:"İş kazası sigortasından doğan haklarda prim günü sınırı aranmaz."},
{c:"İSG",q:"Sürekli iş göremezlik geliri için meslekte kazanma gücü kaybı en az ne olmalıdır?",o:["%5","%10","%25","%50"],a:1,e:"Sürekli iş göremezlik geliri için meslekte kazanma gücü en az %10 oranında azalmış olmalıdır."},
{c:"İSG",q:"Aşağıdakilerden hangisi iş kazası/meslek hastalığı sigortasından sağlanan haklardan DEĞİLDİR?",o:["Geçici iş göremezlik ödeneği","Sürekli iş göremezlik geliri","Ölüm geliri, evlenme, cenaze ödeneği","İşsizlik ödeneği"],a:3,e:"İşsizlik ödeneği ayrı bir sigorta koludur (4447). Diğerleri iş kazası/meslek hastalığından sağlanır."},
{c:"İSG",q:"5510 m.21'e göre işveren hangi durumda Kurumca yapılan ödemelere rücu edilir?",o:["Her iş kazasında","İşverenin kastı veya İSG mevzuatına aykırı hareketi varsa","Sadece ölüm hâlinde","Hiçbir durumda"],a:1,e:"İş kazası/meslek hastalığı işverenin kastı veya İSG mevzuatına aykırı hareketi sonucu olmuşsa Kurum işverene rücu eder."},
{c:"İSG",q:"İşverenin sorumluluğunun tespitinde hangi ilke dikkate alınır (5510 m.21)?",o:["Kusursuz sorumluluk","Kaçınılmazlık ilkesi","Objektif sorumluluk","Mücbir sebep"],a:1,e:"İşverenin sorumluluğunun tespitinde kaçınılmazlık ilkesi dikkate alınır; kaçınılmazlık sorumluluğu sınırlar."},
{c:"İSG",q:"İş kazası/meslek hastalığı üçüncü kişinin kusuruyla olmuşsa Kurum zararın ne kadarını rücu eder?",o:["Tamamını","Yarısını","Üçte birini","Dörtte birini"],a:1,e:"Üçüncü kişinin kusuru hâlinde Kurum mevcut ve gelecekteki zararının yarısını üçüncü kişiye rücu eder (5510 m.21)."},
{c:"İSG",q:"Anayasa'da yaşam hakkı hangi maddelerle ilişkilendirilir?",o:["2-5-17","49-50","56","60"],a:0,e:"Yaşam hakkı Anayasa'nın 2., 5. ve 17. maddeleriyle ilişkilendirilir."},
{c:"İSG",q:"Sosyal güvenlik hakkı Anayasa'nın hangi maddesindedir?",o:["17","49","56","60"],a:3,e:"Sosyal güvenlik hakkı Anayasa'nın 60. maddesindedir (sağlık 56, çalışma 49-50)."},
{c:"İSG",q:"Çalışma ve çalışanların korunması Anayasa'nın hangi maddelerindedir?",o:["2-5","49-50","56-60","17-65"],a:1,e:"Çalışma ve çalışanların korunması Anayasa'nın 49. ve 50. maddelerindedir."},
{c:"Toplu İş",q:"Sendikalar ve Toplu İş Sözleşmesi Kanunu'nun numarası kaçtır?",o:["4857","6331","6356","5510"],a:2,e:"Sendikalar ve Toplu İş Sözleşmesi Kanunu 6356 sayılıdır."},
{c:"Toplu İş",q:"Bir sendika kurmak için en az kaç işçi veya işveren gerekir?",o:["3","5","7","10"],a:2,e:"Sendika en az 7 işçi veya işveren ile kurulur."},
{c:"Toplu İş",q:"Bir konfederasyon kurmak için ne gerekir?",o:["3 sendika","En az 5 ayrı işkolundan sendika","7 işçi","10 işveren"],a:1,e:"Konfederasyon, en az 5 ayrı işkolundan sendikanın bir araya gelmesiyle kurulur."},
{c:"Toplu İş",q:"Sendika kurma hakkı Anayasa'nın hangi maddesindedir?",o:["Madde 49","Madde 51","Madde 56","Madde 60"],a:1,e:"Sendika kurma hakkı Anayasa'nın 51. maddesinde düzenlenir."},
{c:"Toplu İş",q:"Sendikal alanda temel olan ILO sözleşmeleri hangileridir?",o:["87 ve 98","102 ve 121","155 ve 161","100 ve 111"],a:0,e:"Örgütlenme özgürlüğü bakımından ILO 87 ve 98 sayılı sözleşmeler temeldir."},
{c:"Toplu İş",q:"Olumlu (pozitif) bireysel sendika özgürlüğü neyi ifade eder?",o:["Sendikadan ayrılma","Sendika kurma ve üye olma","Greve katılmama","Toplu sözleşme yapmama"],a:1,e:"Olumlu (pozitif) sendika özgürlüğü, sendika kurma ve sendikaya üye olma özgürlüğüdür."},
{c:"Toplu İş",q:"Sendikaya üye olmak için en az kaç yaşını doldurmuş olmak gerekir?",o:["15","16","18","21"],a:0,e:"Sendika üyeliği için işkolunda fiilen çalışan işçi olmak ve 15 yaşını doldurmuş olmak gerekir."},
{c:"Toplu İş",q:"Sendika özgürlüğü güvencesinin ihlalinde işçiye ödenecek sendikal tazminat ne kadardır (m.25)?",o:["En az 6 aylık ücret","En az 1 yıllık ücret","En az 2 yıllık ücret","Bildirim süresinin 3 katı"],a:1,e:"Sendika özgürlüğü ihlalinde işçiye en az bir yıllık ücret tutarında sendikal tazminata hükmedilir (6356 m.25)."},
{c:"Toplu İş",q:"İşyeri sendika temsilcisinin sözleşmesinin feshinde dava açma süresi nedir (m.24)?",o:["6 iş günü","1 ay","2 hafta","2 ay"],a:1,e:"Temsilcinin sözleşmesi haklı neden olmadıkça feshedilemez; fesih tebliğinden itibaren 1 ay içinde dava açılabilir."},
{c:"Toplu İş",q:"İşçi kuruluşu yöneticisi olan işçinin iş sözleşmesi ne olur (m.23)?",o:["Feshedilir","Askıda kalır","Devredilir","Sona erer"],a:1,e:"Yönetici olan işçinin iş sözleşmesi askıda kalır; görevi sona erince 1 ay içinde işe başlatılmak için başvurabilir."},
{c:"Toplu İş",q:"İşyeri toplu iş sözleşmesi için sendikanın yetkisi hangi orana bağlıdır?",o:["%1","%40+1","%50+1","%60"],a:2,e:"İşyeri toplu iş sözleşmesi için işçilerin %50+1'inin sendika üyesi olması gerekir (işletme %40+1)."},
{c:"Toplu İş",q:"İşkolu (yetki) barajı yüzde kaçtır?",o:["%1","%3","%10","%40"],a:0,e:"İşkolu barajı %1'dir."},
{c:"Toplu İş",q:"İşletme toplu iş sözleşmesi için gereken yetki oranı nedir?",o:["%1","%40+1","%50+1","%60"],a:1,e:"İşletme toplu iş sözleşmesi için işçilerin %40+1'inin sendika üyesi olması gerekir."},
{c:"Toplu İş",q:"Toplu iş uyuşmazlığında barışçı çözüm yolu olarak hangisi ZORUNLUDUR?",o:["Grev","Lokavt","Arabuluculuk","Özel hakem"],a:2,e:"Toplu çıkar uyuşmazlıklarında arabuluculuk zorunludur; grev ve lokavt mücadeleci yollardır."},
{c:"Toplu İş",q:"Grev yasakları ve kanunda sayılan hâllerde zorunlu olan organ hangisidir?",o:["İş Mahkemesi","Yüksek Hakem Kurulu","Arabulucu","SGK"],a:1,e:"Grev yasakları ve yasada düzenlenen hâllerde Yüksek Hakem Kurulu'na başvuru zorunludur."},
{c:"Toplu İş",q:"6356 sayılı Kanun'un amacı arasında hangisi YOKTUR?",o:["Toplu iş sözleşmesi yapılması","Uyuşmazlıkların barışçı çözümü","Grev ve lokavt","Bireysel iş sözleşmesinin feshi usulü"],a:3,e:"Bireysel feshin usulü 4857'dedir; 6356 sendika, TİS, barışçı çözüm, grev ve lokavtı düzenler."},
{c:"Sosyal Sigorta",q:"Sosyal güvenlik sistemi hangi iki alt sistemden oluşur?",o:["Primli ve primsiz sistem","Kısa ve uzun vade","Kamu ve özel","Yerel ve ulusal"],a:0,e:"Sosyal güvenlik primli sistem (sosyal sigortalar) ve primsiz sistemden (sosyal yardım/hizmet/tazmin) oluşur."},
{c:"Sosyal Sigorta",q:"ILO 102 sayılı sözleşme kaç sosyal risk sayar?",o:["5","7","9","12"],a:2,e:"ILO 102 sayılı sözleşme 9 sosyal risk sayar (iş kazası-meslek hastalığı, analık, hastalık-gelir kaybı, hastalık-tedavi, yaşlılık, ölüm, maluliyet, işsizlik, aile yardımları)."},
{c:"Sosyal Sigorta",q:"Aşağıdakilerden hangisi KISA vadeli sigorta kollarından DEĞİLDİR?",o:["İş kazası ve meslek hastalığı","Hastalık","Analık","Yaşlılık"],a:3,e:"Yaşlılık uzun vadeli sigorta koludur. KVS: iş kazası/meslek hastalığı, hastalık, analık."},
{c:"Sosyal Sigorta",q:"Aşağıdakilerden hangisi UZUN vadeli sigorta kollarındandır?",o:["İş kazası","Analık","Malullük","Hastalık"],a:2,e:"Uzun vadeli sigorta kolları: malullük, yaşlılık, ölüm."},
{c:"Sosyal Sigorta",q:"Geçici iş göremezlik ödeneği yatarak tedavide günlük kazancın ne kadarıdır?",o:["Yarısı (1/2)","Üçte ikisi (2/3)","Üçte biri","Tamamı"],a:0,e:"Geçici iş göremezlik ödeneği yatarak tedavide günlük kazancın yarısı, ayakta tedavide üçte ikisidir (5510 m.18)."},
{c:"Sosyal Sigorta",q:"Geçici iş göremezlik ödeneği ayakta tedavide günlük kazancın ne kadarıdır?",o:["Yarısı","Üçte ikisi (2/3)","Dörtte üçü","Tamamı"],a:1,e:"Ayakta tedavide geçici iş göremezlik ödeneği günlük kazancın üçte ikisidir (2/3)."},
{c:"Sosyal Sigorta",q:"Hastalık sebebiyle geçici iş göremezlik ödeneği için önceki bir yılda en az kaç gün prim gerekir?",o:["60 gün","90 gün","120 gün","180 gün"],a:1,e:"Hastalıkta geçici iş göremezlik ödeneği için önceki bir yılda en az 90 gün kısa vadeli sigorta primi ve 3. günden itibaren ödenir."},
{c:"Sosyal Sigorta",q:"Sürekli tam iş göremezlikte gelir, kazancın yüzde kaçı üzerinden hesaplanır?",o:["%50","%60","%70","%100"],a:2,e:"Sürekli tam iş göremezlikte gelir kazancın %70'i üzerinden hesaplanır; bakıma muhtaçsa %100."},
{c:"Sosyal Sigorta",q:"İş kazası/meslek hastalığı sonucu ölen sigortalının hak sahiplerine kazancın yüzde kaçı gelir bağlanır?",o:["%50","%60","%70","%100"],a:2,e:"Hak sahiplerine, sigortalının kazancının %70'i gelir olarak bağlanır (5510 m.20)."},
{c:"Sosyal Sigorta",q:"Malul sayılmak için çalışma gücünün veya meslekte kazanma gücünün en az yüzde kaçı kaybedilmiş olmalıdır?",o:["%10","%50","%60","%70"],a:2,e:"Çalışma gücünün veya meslekte kazanma gücünün en az %60'ını kaybeden sigortalı malul sayılır (5510 m.25)."},
{c:"Sosyal Sigorta",q:"Malullük aylığı için en az ne kadar sigortalılık ve kaç gün prim gerekir?",o:["5 yıl / 900 gün","10 yıl / 1800 gün","15 yıl / 3600 gün","20 yıl / 7200 gün"],a:1,e:"Malullük aylığı için malul sayılma + en az 10 yıldan beri sigortalı olup toplam 1800 gün prim gerekir."},
{c:"Sosyal Sigorta",q:"İlk defa 5510'a tabi olanlarda yaşlılık aylığı için yaş şartı nedir?",o:["Kadın 55 / Erkek 58","Kadın 58 / Erkek 60","Kadın 60 / Erkek 65","Kadın-Erkek 65"],a:1,e:"İlk defa bu Kanuna tabi olanlarda kadın 58, erkek 60 yaş; 1/1/2048'den itibaren kadın-erkek 65."},
{c:"Sosyal Sigorta",q:"4/a (hizmet akdiyle çalışan) sigortalılarda yaşlılık aylığı için prim gün şartı nedir?",o:["5400 gün","7200 gün","9000 gün","1800 gün"],a:1,e:"Genel şart 9000 gün; ancak 4/a kapsamındakiler için prim gün sayısı şartı 7200 gün olarak uygulanır."},
{c:"Sosyal Sigorta",q:"Ölüm aylığı için (4/a'da) en az ne kadar sigortalılık ve kaç gün prim alternatifi vardır?",o:["3 yıl / 600 gün","5 yıl / 900 gün","10 yıl / 1800 gün","1 yıl / 360 gün"],a:1,e:"Ölüm aylığı için en az 1800 gün prim veya (4/a'da) en az 5 yıldan beri sigortalı olup 900 gün prim gerekir."},
{c:"Sosyal Sigorta",q:"Aşağıdakilerden hangisi ölüm sigortasından sağlanan haklardan DEĞİLDİR?",o:["Ölüm aylığı","Ölüm toptan ödemesi","Kız çocuklarına evlenme ödeneği","Yaşlılık aylığı"],a:3,e:"Yaşlılık aylığı yaşlılık sigortasındandır. Ölüm sigortası: ölüm aylığı, toptan ödeme, evlenme ödeneği, cenaze ödeneği."},
{c:"Sosyal Sigorta",q:"Sigortalı borçlanma primlerini hangi oran üzerinden öder (5510 m.41)?",o:["%20","%32","%34","%45"],a:1,e:"Borçlanmada, belirlenen günlük kazancın %32'si üzerinden hesaplanan primler ödenir."},
{c:"Sosyal Sigorta",q:"Vazife malullüğü esas olarak hangi sigortalı grubu için söz konusudur (5510 m.47)?",o:["4/a (hizmet akdi)","4/b (bağımsız)","4/c (kamu görevlisi)","İsteğe bağlı"],a:2,e:"Vazife malullüğü, 4/c (kamu görevlisi) kapsamındaki sigortalılar bakımından uygulanır."},
{c:"İşsizlik/GSS",q:"İsteğe bağlı sigortanın (İBS) kapsamı nedir?",o:["Sadece KVS","Sadece GSS","UVS + GSS (KVS yok)","KVS + UVS + GSS"],a:2,e:"İsteğe bağlı sigorta uzun vadeli sigorta ve genel sağlık sigortasını kapsar; kısa vadeli sigorta yoktur."},
{c:"İşsizlik/GSS",q:"İsteğe bağlı sigortalı olmak için kaç yaşını doldurmak gerekir?",o:["16","18","20","21"],a:1,e:"İBS için Türkiye'de ikamet, zorunlu sigortalı olmamak, 18 yaşını doldurmak ve talepte bulunmak gerekir."},
{c:"İşsizlik/GSS",q:"Genel sağlık sigortasından yararlanmak için son bir yılda en az kaç gün prim gerekir (m.67)?",o:["30 gün","60 gün","90 gün","120 gün"],a:0,e:"GSS'den yararlanmak için başvurudan önceki son bir yılda toplam 30 gün GSS primi gerekir."},
{c:"İşsizlik/GSS",q:"İşsizlik sigortası primleri nasıl paylaşılır (4447 m.49)?",o:["%1 sigortalı + %2 işveren + %1 Devlet","%2 sigortalı + %1 işveren","%1 sigortalı + %1 işveren","Tamamı işveren"],a:0,e:"İşsizlik sigortası primi %1 sigortalı, %2 işveren ve %1 Devlet payı olarak alınır."},
{c:"İşsizlik/GSS",q:"İşsizlik ödeneğine hak kazanmak için son 3 yılda en az kaç gün prim gerekir?",o:["360 gün","600 gün","900 gün","1080 gün"],a:1,e:"Son 3 yıl (36 ay) içinde en az 600 gün işsizlik sigortası primi ödenmiş olmalıdır."},
{c:"İşsizlik/GSS",q:"İşsizlik ödeneğine hak kazanmak için sözleşme sona ermeden önceki son kaç gün sürekli çalışma gerekir?",o:["90 gün","120 gün","180 gün","240 gün"],a:1,e:"Sözleşmenin sona ermesinden önceki son 120 gün prim ödeyerek sürekli çalışmış olmak gerekir."},
{c:"İşsizlik/GSS",q:"Günlük işsizlik ödeneği son 4 aylık ortalama brüt kazancın yüzde kaçıdır?",o:["%40","%50","%60","%80"],a:0,e:"Günlük işsizlik ödeneği son 4 aylık prime esas kazancın günlük ortalamasının %40'ıdır."},
{c:"İşsizlik/GSS",q:"İşsizlik ödeneği aylık asgari ücretin brüt tutarının yüzde kaçını geçemez?",o:["%50","%60","%80","%100"],a:2,e:"İşsizlik ödeneği, 16 yaşından büyükler için aylık asgari ücretin brüt tutarının %80'ini geçemez."},
{c:"İşsizlik/GSS",q:"600 gün prim ödeyen sigortalı işsize kaç gün işsizlik ödeneği verilir?",o:["120 gün","180 gün","240 gün","300 gün"],a:1,e:"600 gün → 180 gün; 900 gün → 240 gün; 1080 gün → 300 gün işsizlik ödeneği verilir (m.50)."},
{c:"İşsizlik/GSS",q:"1080 gün prim ödeyen sigortalı işsize kaç gün işsizlik ödeneği verilir?",o:["180 gün","240 gün","300 gün","360 gün"],a:2,e:"1080 gün prim ödeyene 300 gün işsizlik ödeneği verilir."},
{c:"İşsizlik/GSS",q:"İşsiz, hizmet akdinin feshini izleyen kaç gün içinde İŞKUR'a başvurmalıdır?",o:["10 gün","15 gün","30 gün","60 gün"],a:2,e:"Sigortalı işsiz, feshi izleyen günden itibaren 30 gün içinde Kuruma başvurmalıdır; gecikilen süre hak edilen süreden düşülür."},
{c:"İşsizlik/GSS",q:"Madde 51'e göre işveren feshinin işsizlik ödeneğine hak kazandırması için fesih hangi sebebe dayanmamalıdır?",o:["Önelli (bildirimli) fesih","Ahlak ve iyiniyet kurallarına aykırılık","Sağlık sebepleri","İşyerinin kapanması"],a:1,e:"İşveren feshi ahlak ve iyiniyet kurallarına aykırılık (m.25/II) dışında bir sebebe dayanıyorsa işsizlik ödeneğine hak kazanılır."},
{c:"İşsizlik/GSS",q:"Ücret Garanti Fonu hangi durumda devreye girer ve kaç aylık ücreti karşılar?",o:["İşçi istifasında / 1 ay","İşverenin ödeme aczinde / 3 aylık ücret","Grevde / 6 aylık","Emeklilikte / 1 yıl"],a:1,e:"İşverenin ödeme aczine düşmesinde (konkordato, iflas, aciz vesikası) işçinin son bir yıldaki 3 aylık ödenmeyen ücreti karşılanır (Ek m.1)."},
{c:"İşsizlik/GSS",q:"Kısa çalışma ödeneği son 12 aylık ortalama brüt kazancın yüzde kaçıdır?",o:["%40","%50","%60","%80"],a:2,e:"Günlük kısa çalışma ödeneği son 12 aylık ortalama brüt kazancın %60'ıdır; asgari ücretin brüt tutarının %150'sini geçemez (Ek m.2)."},
{c:"İşsizlik/GSS",q:"SGK ve sosyal güvenlik uyuşmazlıklarında dava açmadan önce ne gerekir (7036)?",o:["Arabulucuya başvuru","SGK'ya başvuru zorunludur","Doğrudan dava","Bakanlık izni"],a:1,e:"İş Mahkemeleri Kanunu (7036) m.4'e göre SGK uyuşmazlıklarında dava açmadan önce SGK'ya başvuru zorunludur (60 gün içinde cevap verilmezse reddedilmiş sayılır)."},
{c:"İşsizlik/GSS",q:"Doğum/evlat edinme sonrası yarım çalışma ödeneği için son üç yılda en az kaç gün prim gerekir?",o:["120 gün","450 gün","600 gün","900 gün"],a:2,e:"Yarım çalışma ödeneği için son üç yılda en az 600 gün işsizlik sigortası primi bildirilmiş olmalıdır (Ek m.5)."}
];

const FLASHCARDS = [
{f:"Belirli süreli sözleşmede haklı/derhal fesih hangi maddeler?",b:"<b>m.24</b> (işçi) ve <b>m.25</b> (işveren)."},
{f:"İşverenin temerrüdü hangi madde, sonucu?",b:"<b>TBK m.408</b> — işçiye <b>ücret ödenir</b>; kazanılan/kaçınılan yararlar indirilir."},
{f:"İşçinin usulsüz feshi tazminatı ve süresi (TBK 439)?",b:"<b>Aylık ücretin ¼'ü</b>; hak <b>30 gün</b> içinde kullanılmazsa düşer."},
{f:"Yeni işverenin sorumluluğu hangi madde?",b:"<b>İş K. m.23</b> — sebep olma / bilerek alma / öğrenince çalıştırma."},
{f:"Süreli fesih kim tarafından kullanılır?",b:"<b>Hem işçi hem işveren.</b> Fesheden taraf diğerine bildirim yapar (m.17)."},
{f:"Bildirim süreleri (m.17)?",b:"&lt;6 ay <b>2</b>, 6ay-1,5yıl <b>4</b>, 1,5-3yıl <b>6</b>, 3+yıl <b>8 hafta</b>. Asgari, artırılabilir."},
{f:"Bildirim şartına uymayan taraf ne öder?",b:"Bildirim süresine ilişkin ücret tutarında <b>ihbar tazminatı</b>."},
{f:"Kötüniyet (fesih hakkının kötüye kullanımı) tazminatı?",b:"İş güvencesi dışındaki işçiye <b>bildirim süresinin 3 katı</b>."},
{f:"Esaslı değişiklik kabul süresi (m.22)?",b:"İşçi <b>6 işgünü</b> içinde <b>yazılı</b> kabul etmezse bağlamaz."},
{f:"İşçi haklı fesih başlıkları (m.24)?",b:"I. Sağlık · II. Ahlak ve iyiniyet · III. Zorlayıcı (<b>1 haftadan fazla</b> durma)."},
{f:"İşveren haklı fesih başlıkları (m.25)?",b:"I. Sağlık · II. Ahlak/iyiniyet · III. Zorlayıcı · IV. <b>Gözaltı/tutukluluk</b>."},
{f:"m.25 sağlık devamsızlık rakamları?",b:"Kendi kusurundan ardı ardına <b>3 iş günü</b> / ayda <b>5 iş gününden</b> fazla."},
{f:"m.25 ahlak: devamsızlık ve hapis?",b:"İzinsiz ardı ardına <b>2 işgünü</b> / ayda <b>3 işgünü</b>; <b>7 günden fazla hapis</b>."},
{f:"Derhal fesih süresi (m.26)?",b:"Öğrenmeden <b>6 iş günü</b>, her hâlde fiilden <b>1 yıl</b>."},
{f:"Fesihte usul (m.19)?",b:"<b>Yazılı</b>, sebep <b>açık-kesin</b>; davranış/verim fesihinde <b>savunma alınır</b>."},
{f:"İş güvencesi şartları?",b:"<b>30+ işçi · 6 ay kıdem · belirsiz süreli · işveren vekili olmamak.</b> Yer altında kıdem aranmaz."},
{f:"İşe iade itiraz süreleri (m.20)?",b:"<b>1 ay arabulucu</b> → <b>2 hafta dava</b>. İspat <b>işverende</b>."},
{f:"Geçersiz fesih sonuçları (m.21)?",b:"<b>1 ay</b> işe başlat → yoksa <b>4-8 ay</b> tazminat + <b>4 ay</b> boşta ücret; başvuru <b>10 işgünü</b>."},
{f:"Geçerli sebep oluşturmayan haller?",b:"Sendika üyeliği/faaliyeti, temsilcilik, idari-adli başvuru, ırk/cinsiyet/din/hamilelik, m.74 izinleri."},
{f:"Kıdem tazminatı hangi kanun/madde?",b:"<b>Mülga 1475 m.14</b> (yürürlükteki tek madde)."},
{f:"Kıdem tazminatı miktarı ve şartı?",b:"Her tam yıl için <b>30 günlük ücret</b>, <b>son ücret</b> üzerinden, en az <b>1 yıl</b> kıdem."},
{f:"Kadın evlilik nedeniyle kıdem tazminatı?",b:"Evlendiği tarihten itibaren <b>1 yıl içinde</b> kendi isteğiyle ayrılırsa hak kazanır."},
{f:"İş hukukunda zamanaşımı (Ek m.3)?",b:"Kıdem, ihbar, kötüniyet, eşit davranma tazminatı ve izin ücretinde <b>5 yıl</b>."},
{f:"Ücret ne sıklıkla ödenir, zamanaşımı?",b:"En geç <b>ayda bir</b> (banka); ücret alacağı zamanaşımı <b>5 yıl</b>."},
{f:"m.34 — ücret kaç günde ödenmezse?",b:"<b>20 gün</b> içinde ödenmeyince işçi iş görmekten kaçınabilir (grev sayılmaz)."},
{f:"m.35 — ücretin haczi?",b:"Ücretin <b>dörtte birinden fazlası haczedilemez</b> (nafaka hariç)."},
{f:"Yeni iş arama izni (m.27)?",b:"Günde en az <b>2 saat</b> ücretli; izinde çalıştırılırsa <b>%100 zamlı</b>."},
{f:"Toplu işçi çıkarma bildirimi ve eşikler?",b:"<b>30 gün</b> önce bildirim. 20-100→<b>10</b>, 101-300→<b>%10</b>, 301+→<b>30</b> işçi."},
{f:"Haftalık azami çalışma süresi?",b:"<b>45 saat</b> (yer altı maden <b>37,5</b>; günlük max <b>7,5</b>)."},
{f:"Denkleştirme süreleri?",b:"<b>2 ay</b> (TİS 4); turizm <b>4 ay</b> (TİS 6); günlük max <b>11 saat</b>; ort. 45."},
{f:"Telafi çalışması kuralları?",b:"<b>Fazla çalışma sayılmaz</b>; günde en çok <b>3 saat</b>; tatilde yok."},
{f:"Kısa çalışma nedir?",b:"Kriz/zorlayıcı sebeple <b>3 ay</b>, en az <b>1/3 azaltma</b> veya <b>4 hafta</b> durma."},
{f:"Ara dinlenme süreleri (m.68)?",b:"≤4 saat <b>15 dk</b>; 4-7,5 saat <b>30 dk</b>; >7,5 saat <b>1 saat</b>. Çalışma süresinden sayılmaz."},
{f:"Gece dönemi ve gece çalışması (m.69)?",b:"Gece <b>20.00-06.00</b>, max 11 saat; gece çalışması <b>7,5 saati</b> geçemez."},
{f:"Çocuk çalıştırma yaşı (m.71)?",b:"<b>15 yaşını</b> doldurmamış çocuk çalıştırılamaz (14+ hafif işler)."},
{f:"Yer/su altı çalıştırma yasağı (m.72)?",b:"<b>18 yaş altı erkek</b> ve <b>her yaştaki kadın</b> çalıştırılamaz."},
{f:"Analık izni (m.74)?",b:"Doğum öncesi 8 + sonrası 8 = <b>16 hafta</b>; çoğulda <b>+2</b>; süt izni <b>1,5 saat</b>."},
{f:"Yarım çalışma ücretsiz izni?",b:"1. doğum <b>60</b>, 2. <b>120</b>, sonraki <b>180</b> gün (engelli 360)."},
{f:"Fazla çalışma vs fazla süreli çalışma?",b:"45 üstü = fazla çalışma <b>%50</b>; 45 altı belirlenip aşma = fazla süreli <b>%25</b>."},
{f:"Fazla çalışma onay ve yıllık sınır?",b:"<b>İşçi onayı</b> şart; yılda en çok <b>270 saat</b>."},
{f:"Serbest zaman karşılığı?",b:"Fazla çalışma <b>1,5 saat</b>; fazla süreli <b>1,25 saat</b> (6 ay içinde)."},
{f:"Fazla çalışma yaptırılamayanlar?",b:"<b>18 yaş altı</b>, gebe/emziren, raporlu, <b>kısmi süreli</b>, yer altı maden işçisi."},
{f:"Hafta tatili (m.46)?",b:"7 günlük dilimde kesintisiz en az <b>24 saat</b>; ücreti tam ödenir."},
{f:"Mazeret izni (Ek m.2)?",b:"Evlenme/ölüm <b>3 gün</b>; eş doğum <b>5 gün</b>; engelli çocuk tedavisi <b>10 gün</b>."},
{f:"Yıllık izin süreleri (m.53)?",b:"1-5 yıl <b>14</b>, 5-15 yıl <b>20</b>, 15+ yıl <b>26 gün</b>. Yer altı +4."},
{f:"Yıllık izne hak kazanma?",b:"En az <b>1 yıl</b> çalışma (deneme dâhil). Haktan <b>vazgeçilemez</b>."},
{f:"18 yaş altı / 50+ yaş yıllık izin?",b:"En az <b>20 gün</b>."},
{f:"Kısmi süreli çalışma?",b:"Emsalin <b>2/3'ü</b> → 45 saat için <b>30 saat ve altı</b>. Fazla çalışma yaptırılamaz."},
{f:"İSG iki ekseni?",b:"<b>Koruma</b> (6331 - önleme) ve <b>Telafi</b> (5510 - gelir güvencesi)."},
{f:"İşverenin İSG sağlama borcu?",b:"<b>TBK m.417</b> — işveren önlem alır, işçi önlemlere uyar."},
{f:"İş kazası tanımı hangi madde?",b:"<b>6331 m.3/g</b> ve <b>5510 m.13</b>."},
{f:"Meslek hastalığı tanımı?",b:"<b>6331 m.3/l</b>: mesleki risklere maruziyet sonucu hastalık. <b>5510 m.14</b>."},
{f:"Servis (işveren taşıtı) kazası?",b:"İşe gidiş-gelişte işverence sağlanan taşıttaki kaza <b>iş kazasıdır</b>."},
{f:"İş kazası bildirim süresi?",b:"Kolluğa <b>derhal</b>, SGK'ya <b>3 işgünü</b> içinde."},
{f:"İş kazasında prim gün şartı?",b:"<b>Aranmaz.</b>"},
{f:"Sürekli iş göremezlik geliri kayıp oranı?",b:"Meslekte kazanma gücü <b>en az %10</b> azalma."},
{f:"İş kazası/meslek hastalığı hakları?",b:"Geçici/sürekli iş göremezlik, <b>ölüm geliri, evlenme, cenaze ödeneği</b>."},
{f:"Rücu şartı (5510 m.21)?",b:"İşverenin <b>kastı</b> veya <b>İSG mevzuatına aykırı</b> hareketi. Kaçınılmazlık sorumluluğu sınırlar."},
{f:"3. kişi kusurunda rücu?",b:"Zararın <b>yarısı</b> üçüncü kişiye rücu edilir."},
{f:"Anayasal haklar (İSG)?",b:"Yaşam <b>2-5-17</b>, sağlık <b>56</b>, çalışma <b>49-50</b>, sosyal güvenlik <b>60</b>."},
{f:"Toplu iş hukuku kanunu?",b:"<b>6356 sayılı</b> Sendikalar ve Toplu İş Sözleşmesi Kanunu."},
{f:"Sendika ve konfederasyon kuruluş sayısı?",b:"Sendika <b>7 işçi/işveren</b>; konfederasyon <b>5 işkolu sendika</b>."},
{f:"Sendika kurma hakkı Anayasa maddesi?",b:"<b>m.51</b>. ILO <b>87 ve 98</b>."},
{f:"Sendika üyelik yaşı?",b:"<b>15 yaşını</b> doldurmuş, işkolunda fiilen çalışan işçi."},
{f:"Olumlu / olumsuz sendika özgürlüğü?",b:"Olumlu = <b>kurma/üye olma</b>; olumsuz = <b>ayrılma/üye olmama</b>."},
{f:"Sendikal tazminat (m.25)?",b:"<b>En az 1 yıllık ücret</b>; ispat yükü işverende."},
{f:"Temsilcilik güvencesi (m.24)?",b:"Haklı neden olmadıkça fesih yok; <b>1 ay dava</b>, <b>6 iş günü</b> başvuru."},
{f:"Yöneticilik güvencesi (m.23)?",b:"Sözleşme <b>askıda</b>; görev sonrası <b>1 ay</b> içinde başvuru."},
{f:"Toplu iş sözleşmesi yetki barajları?",b:"İşkolu <b>%1</b>, işyeri <b>%50+1</b>, işletme <b>%40+1</b>."},
{f:"Uyuşmazlık çözüm yolları?",b:"Barışçı: <b>arabulucu (zorunlu)</b>, YHK. Mücadeleci: <b>grev/lokavt</b>."},
{f:"Sosyal güvenlik iki sistem?",b:"<b>Primli</b> (sigorta) + <b>primsiz</b> (yardım/hizmet/tazmin)."},
{f:"ILO 102 kaç risk?",b:"<b>9 sosyal risk.</b>"},
{f:"5510 üç sigorta kolu?",b:"<b>KVS</b> (iş kazası/m.h., hastalık, analık), <b>UVS</b> (malullük, yaşlılık, ölüm), <b>GSS</b>."},
{f:"Geçici iş göremezlik ödeneği oranları?",b:"Yatarak <b>½</b>, ayakta <b>⅔</b>; hastalıkta <b>90 gün prim + 3. gün</b>."},
{f:"Sürekli iş göremezlik: tam ve bakıma muhtaç?",b:"Tam <b>%70</b>; bakıma muhtaç <b>%100</b>; kayıp <b>≥%10</b>."},
{f:"Hak sahibine bağlanan gelir oranı?",b:"Kazancın <b>%70'i</b> (5510 m.20)."},
{f:"Malullük şartları?",b:"Çalışma gücü kaybı <b>%60</b> + <b>10 yıl</b> sigortalı + <b>1800 gün</b> prim."},
{f:"Yaşlılık aylığı yaş ve prim?",b:"Kadın <b>58</b>/erkek <b>60</b>; <b>9000 gün</b> (4/a → <b>7200</b>); 2048→65."},
{f:"Ölüm aylığı prim şartı?",b:"<b>1800 gün</b> veya (4/a) <b>5 yıl + 900 gün</b>."},
{f:"Vazife malullüğü kimde?",b:"<b>4/c</b> (kamu görevlisi)."},
{f:"İsteğe bağlı sigorta kapsamı?",b:"<b>UVS + GSS</b> (KVS yok); <b>18 yaş</b>, zorunlu sigortalı olmamak."},
{f:"GSS yararlanma şartı (m.67)?",b:"Son yılda <b>30 gün</b> prim; (bazı bentlerde) <b>60 günden fazla borç olmaması</b>."},
{f:"İşsizlik sigortası prim oranları?",b:"<b>%1 sigortalı + %2 işveren + %1 Devlet.</b>"},
{f:"İşsizlik ödeneği hak kazanma?",b:"Son 3 yılda <b>600 gün</b> + son <b>120 gün</b> sürekli çalışma."},
{f:"İşsizlik ödeneği miktarı?",b:"Son 4 ay ortalamasının <b>%40'ı</b>; max asgari brüt <b>%80</b>."},
{f:"İşsizlik ödeneği süreleri?",b:"600→<b>180</b>, 900→<b>240</b>, 1080→<b>300 gün</b>."},
{f:"İşsizlik ödeneği başvuru süresi?",b:"Fesihten itibaren <b>30 gün</b> içinde İŞKUR'a."},
{f:"İşsizlik ödeneğine hak kazandırmayan fesih?",b:"İşverenin <b>ahlak ve iyiniyete aykırılık (m.25/II)</b> nedenli feshi."},
{f:"Ücret Garanti Fonu?",b:"İşverenin ödeme aczinde işçinin <b>3 aylık</b> ödenmeyen ücreti karşılanır."},
{f:"Kısa çalışma ödeneği miktarı?",b:"Son 12 ay ortalamasının <b>%60'ı</b>; max asgari brüt <b>%150</b>."},
{f:"SGK uyuşmazlığında dava şartı (7036)?",b:"Önce <b>SGK'ya başvuru zorunlu</b> (60 günde cevap yoksa reddedilmiş sayılır)."},
{f:"TBK 408 vs TBK 439?",b:"408 = <b>işverenin temerrüdü</b> (ücret öder); 439 = <b>işçinin usulsüz feshi</b> (¼ ücret tazminat)."},
{f:"İş kazası 5510 m.13 hâlleri (örnek)?",b:"İşyerinde bulunma, iş nedeniyle, görevle başka yere gitme, süt verme, <b>servis taşıtı</b>."},
{f:"Madde 25/I — 6 hafta kuralı?",b:"Diğer hastalık/kaza/doğum hâllerinde işverenin bildirimsiz feshi, bildirim süresini <b>6 hafta</b> aşınca doğar."},
{f:"Borçlanma prim oranı (5510 m.41)?",b:"Belirlenen günlük kazancın <b>%32'si</b>."},
{f:"Yarım çalışma ödeneği prim şartı?",b:"Son 3 yılda <b>600 gün</b> işsizlik sigortası primi."},
{f:"Madde 19 — fesih bildirimi nasıl yapılır?",b:"<b>Yazılı</b>, sebep <b>açık ve kesin</b> belirtilir."},
{f:"İş güvencesi davası süreci kısaca?",b:"Fesih → <b>1 ay arabulucu</b> → <b>2 hafta dava</b> → geçersizse <b>1 ay</b> işe başlat."},
{f:"Madde 73 — sanayide gece yasağı?",b:"<b>18 yaşını doldurmamış</b> çocuk ve genç işçiler gece çalıştırılamaz."},
{f:"Çalışma süresinden sayılmayan süre?",b:"Sosyal yardım amaçlı <b>servis</b> süresi ve <b>ara dinlenmeleri</b> sayılmaz."}
];
